package com.example.planner.utils

const val PLAN_TITLE_MIN_LENGTH = 5
const val PLAN_TITLE_MAX_LENGTH = 50

const val DB_NAME = "DB"

const val NOTIFICATION_ID = 1
const val NOTIFICATION_CHANNEL_ID = "NOTIFICATION_CHANNEL_ID"
const val NOTIFICATION_CHANNEL_NAME = "NOTIFICATION_CHANNEL_NAME"
const val NOTIFICATION_CHANNEL_DESCRIPTION = "NOTIFICATION_CHANNEL_DESCRIPTION"

const val DATE_TIME_FORMAT = "dd.MM.yyyy HH:mm:ss"
const val DATE_TIME_MULTI_LINE_FORMAT = "dd.MM\nHH:mm"

const val NETWORK_TIMEOUT = 5L
